name = "Loki's Vanilla++"
author = "TheFantasticLoki"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "822041633e5e064904f192e74847cd9a37beac017fa6c4e06bc89f9404d56fe0"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
