name = "Loki's Vanilla++"
author = "TheFantasticLoki"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e111e73404289f03915081e98e63c19a3d9c66b20190ac297a8f546428dd4f2c"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
