name = "Loki's Vanilla++"
author = "TheFantasticLoki"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a03342b4024ab45ac3367f44fb157af2974115afabfbbee2d9935642d3334be2"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
