name = "Loki's Vanilla++"
author = "TheFantasticLoki"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "455f4be7d8955b350ca31566caff88f55db87726ae4053b699f3359e02d19eca"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
