name = "Loki's Vanilla++"
author = "TheFantasticLoki"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e5138610eaddfbb866a7b7df54b870186c34aaf2e8df753fbc55c3b03672f5d"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
