name = "Loki's Vanilla++"
author = "TheFantasticLoki"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0811586ffce67bfa2af8bb0c04690cec176e229f5eace59371f99fea67b6ff1e"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
